version: "3.8"

services:
  backend:
    container_name: server
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - DB_URL=mongodb://database/yolomy
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app
    depends_on:
      - database
    ports:
      - "5000:5000"
    networks:
      - yolonetwork  

  mongodb:
    container_name: database
    image: mongo:4.0
    restart: on-failure
    environment: 
      -  MONGO_INITDB_ROOT_USERNAME=root
      -  MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - "27017:27017"
    volumes:
      - database:/data/db
    networks:
      - yolonetwork  

  client:
    container_name: frontend
    build: 
      context: ./client
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    ports:
      - "3000:3000"
    depends_on: 
      - server 
    networks:
      - yolonetwork

volumes:
  database:

networks:
  yolonetwork: